/*
 * 
 */
package carinventory;

import java.util.ArrayList;

/**
 *
 * @author Sukhjinder
 */
public class UI extends javax.swing.JFrame {

        ArrayList<Car> cars = new ArrayList<>();

//      Car Properties  
        String vin;
        String make;
        String model;
        String year;
        String color;
        double price;
        String weight;
        String driveTrain;
        String bodyStyle;
        String mileage;
        String fuelType;
        
//      Engine Properties
        String displacement;
        String numOfCylinders;
        String engineModel;
        String horsepower;
        String torque;
        
//      Transmission Properties
        String type;
        String transModel;
        String numOfGears;
        
        Car car;
        Engine engine;
        Transmission transmission;
        
  
    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        addCarPanel = new javax.swing.JPanel();
        carLabel = new javax.swing.JLabel();
        engineLabel = new javax.swing.JLabel();
        transmissionLabel = new javax.swing.JLabel();
        vinLabel = new javax.swing.JLabel();
        makeLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        drivetrainLabel = new javax.swing.JLabel();
        bodystyleLabel = new javax.swing.JLabel();
        mileageLabel = new javax.swing.JLabel();
        fuelTypeLabel = new javax.swing.JLabel();
        displacementLabel = new javax.swing.JLabel();
        numOfCylindersLabel = new javax.swing.JLabel();
        engineModelLabel = new javax.swing.JLabel();
        horsepowerLabel = new javax.swing.JLabel();
        torqueLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        transModelLabel = new javax.swing.JLabel();
        numOfGearsLabel = new javax.swing.JLabel();
        addCarButton = new javax.swing.JButton();
        vinTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        colorTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        weightTextField = new javax.swing.JTextField();
        mileageTextField = new javax.swing.JTextField();
        displacementTextField = new javax.swing.JTextField();
        engineModelTextField = new javax.swing.JTextField();
        horsepowerTextField = new javax.swing.JTextField();
        torqueTextField = new javax.swing.JTextField();
        transModelTextField = new javax.swing.JTextField();
        driveTrainComboBox = new javax.swing.JComboBox<>();
        bodyStyleComboBox = new javax.swing.JComboBox<>();
        fuelTypeComboBox = new javax.swing.JComboBox<>();
        numOfCylindersComboBox = new javax.swing.JComboBox<>();
        transTypeComboBox = new javax.swing.JComboBox<>();
        numOfGearsComboBox = new javax.swing.JComboBox<>();
        makeComboBox = new javax.swing.JComboBox<>();
        deleteCarPanel = new javax.swing.JPanel();
        enterVINLabel = new javax.swing.JLabel();
        vinDeleteCarTextField = new javax.swing.JTextField();
        jScrollPane = new javax.swing.JScrollPane();
        carDetailsTextArea = new javax.swing.JTextArea();
        removeCarButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        listInventoryPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carListTextArea = new javax.swing.JTextArea();
        loadButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        carLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        carLabel.setText("Car");

        engineLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        engineLabel.setText("Engine");

        transmissionLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        transmissionLabel.setText("Transmission");

        vinLabel.setText("VIN");

        makeLabel.setText("Make");

        modelLabel.setText("Model");

        yearLabel.setText("Year");

        colorLabel.setText("Color");

        priceLabel.setText("Price");

        weightLabel.setText("Weight");

        drivetrainLabel.setText("Drivetrain");

        bodystyleLabel.setText("Bodystyle");

        mileageLabel.setText("Mileage");

        fuelTypeLabel.setText("Fuel Type");

        displacementLabel.setText("Displacement");

        numOfCylindersLabel.setText("Number of Cylinders");

        engineModelLabel.setText("Model");

        horsepowerLabel.setText("Horsepower");

        torqueLabel.setText("Torque");

        typeLabel.setText("Type");

        transModelLabel.setText("Model");

        numOfGearsLabel.setText("Number of Gears");

        addCarButton.setText("Add Car");
        addCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarButtonActionPerformed(evt);
            }
        });

        horsepowerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horsepowerTextFieldActionPerformed(evt);
            }
        });

        transModelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transModelTextFieldActionPerformed(evt);
            }
        });

        driveTrainComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RWD", "FWD", "AWD", "4x4", "4WD" }));

        bodyStyleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coupe", "Sedan", "SUV", "Convertible", "Pickup", "Hatchback", "Wagon", "Minivan", "Van" }));

        fuelTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gas", "Diesel", "E85", "Electric", "Natural Gas" }));

        numOfCylindersComboBox.setEditable(true);
        numOfCylindersComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "8", "10", "12" }));

        transTypeComboBox.setEditable(true);
        transTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Automatic", "AutoManual", "CVT" }));

        numOfGearsComboBox.setEditable(true);
        numOfGearsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        makeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acura", "Alfa Romeo", "Aston Martin", "Audi", "Bentley", "BMW", "Buick", "Cadillac", "Chevrolet", "Chrysler", "Dodge", "Ferrari", "Fiat", "Ford", "Genesis", "GMC", "Honda", "Hyundai", "Infiniti", "Jaguar", "Jeep", "Kia", "Lamborghini", "Land Rover", "Lexus", "Lincoln", "Maserati", "Mazda", "McLaren", "Mercedes-Benz", "Mercury", "MINI", "Mitsubishi", "Nissan", "Pontiac", "Porsche", "RAM", "Rolls-Royce", "Saturn", "Scion", "Smart", "Subaru", "Tesla", "Toyota", "Volkswagen", "Volvo" }));

        javax.swing.GroupLayout addCarPanelLayout = new javax.swing.GroupLayout(addCarPanel);
        addCarPanel.setLayout(addCarPanelLayout);
        addCarPanelLayout.setHorizontalGroup(
            addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCarPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(carLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(engineLabel)
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCarPanelLayout.createSequentialGroup()
                .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCarPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colorLabel)
                            .addComponent(priceLabel)
                            .addComponent(yearLabel)
                            .addComponent(modelLabel)
                            .addComponent(makeLabel)
                            .addComponent(vinLabel)
                            .addComponent(weightLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drivetrainLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bodystyleLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mileageLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fuelTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vinTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modelTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(yearTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(priceTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(weightTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(makeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 163, Short.MAX_VALUE)
                    .addComponent(bodyStyleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mileageTextField)
                    .addComponent(fuelTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(driveTrainComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCarPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addCarPanelLayout.createSequentialGroup()
                                .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addCarPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(numOfCylindersLabel)
                                            .addComponent(displacementLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(displacementTextField)
                                            .addComponent(engineModelTextField)
                                            .addComponent(horsepowerTextField)
                                            .addComponent(torqueTextField)
                                            .addComponent(numOfCylindersComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCarPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(transTypeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(transModelTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCarPanelLayout.createSequentialGroup()
                                .addGap(0, 32, Short.MAX_VALUE)
                                .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCarPanelLayout.createSequentialGroup()
                                        .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(engineModelLabel)
                                            .addComponent(horsepowerLabel)
                                            .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(typeLabel)
                                                .addComponent(torqueLabel)
                                                .addComponent(transModelLabel)))
                                        .addGap(214, 214, 214))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCarPanelLayout.createSequentialGroup()
                                        .addComponent(transmissionLabel)
                                        .addGap(71, 71, 71))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCarPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(numOfGearsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numOfGearsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        addCarPanelLayout.setVerticalGroup(
            addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carLabel)
                    .addComponent(engineLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vinLabel)
                    .addComponent(displacementLabel)
                    .addComponent(vinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displacementTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makeLabel)
                    .addComponent(numOfCylindersLabel)
                    .addComponent(numOfCylindersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLabel)
                    .addComponent(engineModelLabel)
                    .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(engineModelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(horsepowerLabel)
                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horsepowerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorLabel)
                    .addComponent(torqueLabel)
                    .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(torqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCarPanelLayout.createSequentialGroup()
                        .addComponent(transmissionLabel)
                        .addGap(18, 18, 18)
                        .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeLabel)
                            .addComponent(transTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addCarPanelLayout.createSequentialGroup()
                        .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weightLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drivetrainLabel)
                            .addComponent(driveTrainComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCarPanelLayout.createSequentialGroup()
                        .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transModelLabel)
                            .addComponent(transModelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numOfGearsLabel)
                            .addComponent(numOfGearsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addCarPanelLayout.createSequentialGroup()
                        .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bodystyleLabel)
                            .addComponent(bodyStyleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mileageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mileageLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fuelTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fuelTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jTabbedPane.addTab("Add Car", addCarPanel);

        enterVINLabel.setText("Enter VIN");

        carDetailsTextArea.setEditable(false);
        carDetailsTextArea.setColumns(20);
        carDetailsTextArea.setRows(5);
        jScrollPane.setViewportView(carDetailsTextArea);

        removeCarButton.setText("Remove Car");
        removeCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCarButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteCarPanelLayout = new javax.swing.GroupLayout(deleteCarPanel);
        deleteCarPanel.setLayout(deleteCarPanelLayout);
        deleteCarPanelLayout.setHorizontalGroup(
            deleteCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteCarPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(deleteCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane)
                    .addGroup(deleteCarPanelLayout.createSequentialGroup()
                        .addComponent(enterVINLabel)
                        .addGap(18, 18, 18)
                        .addComponent(vinDeleteCarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton)
                        .addContainerGap(115, Short.MAX_VALUE))))
            .addGroup(deleteCarPanelLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(removeCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        deleteCarPanelLayout.setVerticalGroup(
            deleteCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteCarPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(deleteCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterVINLabel)
                    .addComponent(vinDeleteCarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeCarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Delete Car", deleteCarPanel);

        carListTextArea.setEditable(false);
        carListTextArea.setColumns(20);
        carListTextArea.setRows(5);
        jScrollPane1.setViewportView(carListTextArea);

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listInventoryPanelLayout = new javax.swing.GroupLayout(listInventoryPanel);
        listInventoryPanel.setLayout(listInventoryPanelLayout);
        listInventoryPanelLayout.setHorizontalGroup(
            listInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(listInventoryPanelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        listInventoryPanelLayout.setVerticalGroup(
            listInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listInventoryPanelLayout.createSequentialGroup()
                .addComponent(loadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane.addTab("List Inventory", listInventoryPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarButtonActionPerformed
        
        vin = vinTextField.getText();
        make = makeComboBox.getSelectedItem().toString();
        model = modelTextField.getText();
        year = yearTextField.getText();
        color = colorTextField.getText();
        price = Double.parseDouble(priceTextField.getText());
        weight = weightTextField.getText();
        driveTrain = driveTrainComboBox.getSelectedItem().toString();
        bodyStyle = bodyStyleComboBox.getSelectedItem().toString();
        mileage = mileageTextField.getText();
        fuelType = fuelTypeComboBox.getSelectedItem().toString();
        displacement = displacementTextField.getText();
        numOfCylinders = numOfCylindersComboBox.getSelectedItem().toString();
        engineModel = engineModelTextField.getText();
        horsepower = horsepowerTextField.getText();
        torque = torqueTextField.getText();
        type = transTypeComboBox.getSelectedItem().toString();
        transModel = transModelTextField.getText();
        numOfGears = numOfGearsComboBox.getSelectedItem().toString();
        
        car = new Car();
        engine = new Engine();
        transmission = new Transmission();
                
        car.setVin(vin);
        car.setMake(make);
        car.setModel(model);
        car.setYear(year);
        car.setColor(color);
        car.setPrice(price);
        car.setWeight(weight);
        car.setDriveTrain(driveTrain);
        car.setBodyStyle(bodyStyle);
        car.setMileage(mileage);
        car.setFuelType(fuelType);
                
        engine.setDisplacement(displacement);
        engine.setNumOfCylinders(numOfCylinders);
        engine.setModel(engineModel);
        engine.setHorsepower(horsepower);
        engine.setTorque(torque);
        engine.setVIN(vin);
                
        transmission.setType(type);
        transmission.setModel(transModel);
        transmission.setNumOfGears(numOfGears);
        transmission.setVin(vin);
               
        car.setEngine(engine);
        car.setTransmission(transmission);
               
                
        cars.add(car);
                
        DBAccess.addCar(car);
        DBAccess.addEngine(engine);
        DBAccess.addTransmission(transmission);
        
        vinTextField.setText("");
        modelTextField.setText("");
        yearTextField.setText("");
        colorTextField.setText("");
        priceTextField.setText("");
        weightTextField.setText("");
        mileageTextField.setText("");
        displacementTextField.setText("");
        engineModelTextField.setText("");
        horsepowerTextField.setText("");
        torqueTextField.setText("");
        transModelTextField.setText("");
                        
    }//GEN-LAST:event_addCarButtonActionPerformed

    private void horsepowerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horsepowerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horsepowerTextFieldActionPerformed

    private void removeCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCarButtonActionPerformed
        String VIN = vinDeleteCarTextField.getText();
        DBAccess.deleteCar(VIN);
    }//GEN-LAST:event_removeCarButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        
        String VIN = vinDeleteCarTextField.getText();
        Car car1 = DBAccess.retrieveByVIN(VIN);
        if(car1==null){
            carDetailsTextArea.setText("No Matching VIN Found");
        }
        else{
            carDetailsTextArea.setText(car1.toString());
        }
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        ArrayList<Car> cars = new ArrayList<>();
        cars = DBAccess.retrieveCars();
        String output = "";

        if(cars!=null){
            for(int i=0; i<cars.size(); i++){
                
                output+= cars.get(i).toString();
            }
            carListTextArea.setText(output);
        }
        
        else{
            carListTextArea.setText("No Cars in Inventory");
        }
    }//GEN-LAST:event_loadButtonActionPerformed

    private void transModelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transModelTextFieldActionPerformed
        
    }//GEN-LAST:event_transModelTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCarButton;
    private javax.swing.JPanel addCarPanel;
    private javax.swing.JComboBox<String> bodyStyleComboBox;
    private javax.swing.JLabel bodystyleLabel;
    private javax.swing.JTextArea carDetailsTextArea;
    private javax.swing.JLabel carLabel;
    private javax.swing.JTextArea carListTextArea;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JPanel deleteCarPanel;
    private javax.swing.JLabel displacementLabel;
    private javax.swing.JTextField displacementTextField;
    private javax.swing.JComboBox<String> driveTrainComboBox;
    private javax.swing.JLabel drivetrainLabel;
    private javax.swing.JLabel engineLabel;
    private javax.swing.JLabel engineModelLabel;
    private javax.swing.JTextField engineModelTextField;
    private javax.swing.JLabel enterVINLabel;
    private javax.swing.JComboBox<String> fuelTypeComboBox;
    private javax.swing.JLabel fuelTypeLabel;
    private javax.swing.JLabel horsepowerLabel;
    private javax.swing.JTextField horsepowerTextField;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JPanel listInventoryPanel;
    private javax.swing.JButton loadButton;
    private javax.swing.JComboBox<String> makeComboBox;
    private javax.swing.JLabel makeLabel;
    private javax.swing.JLabel mileageLabel;
    private javax.swing.JTextField mileageTextField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JComboBox<String> numOfCylindersComboBox;
    private javax.swing.JLabel numOfCylindersLabel;
    private javax.swing.JComboBox<String> numOfGearsComboBox;
    private javax.swing.JLabel numOfGearsLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JButton removeCarButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel torqueLabel;
    private javax.swing.JTextField torqueTextField;
    private javax.swing.JLabel transModelLabel;
    private javax.swing.JTextField transModelTextField;
    private javax.swing.JComboBox<String> transTypeComboBox;
    private javax.swing.JLabel transmissionLabel;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField vinDeleteCarTextField;
    private javax.swing.JLabel vinLabel;
    private javax.swing.JTextField vinTextField;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JTextField weightTextField;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
